version: "3"

services:
  mosquitto-brocker:
    container_name: mosquitto
    image: docker.io/library/eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:Z
      - ./mosquitto/log/:/mosquitto/log/:Z
      - ./mosquitto/data/:/mosquitto/data/:Z
    network_mode: host
